version: '3'
services:

  web:
    build: ./php/
    container_name: web
    restart: always
    ports:
      - 80:80
    volumes:
      - ./frontend:/var/www/html
    links:
      - pgsql
  pgsql:
      image: postgres
      restart: always
      ports:
        - 5432:5432
      environment:
        POSTGRES_PASSWORD: postgres
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080